{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "a63ddf14",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.\n",
      "/Users/amitpatel/Developer/PythonFiles/Image-Classification-Cat-v-Dog/.venv/lib/python3.13/site-packages/gradio/interface.py:415: UserWarning: The `allow_flagging` parameter in `Interface` is deprecated. Use `flagging_mode` instead.\n",
      "  warnings.warn(\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      " Model 'cat_dog_cnn_91_accuracy.h5' loaded successfully.\n",
      "* Running on local URL:  http://127.0.0.1:7866\n",
      "* To create a public link, set `share=True` in `launch()`.\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "<div><iframe src=\"http://127.0.0.1:7866/\" width=\"100%\" height=\"500\" allow=\"autoplay; camera; microphone; clipboard-read; clipboard-write;\" frameborder=\"0\" allowfullscreen></iframe></div>"
      ],
      "text/plain": [
       "<IPython.core.display.HTML object>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "text/plain": []
     },
     "execution_count": 10,
     "metadata": {},
     "output_type": "execute_result"
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:    Exception in ASGI application\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/amitpatel/Developer/PythonFiles/Image-Classification-Cat-v-Dog/.venv/lib/python3.13/site-packages/uvicorn/protocols/http/h11_impl.py\", line 403, in run_asgi\n",
      "    result = await app(  # type: ignore[func-returns-value]\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "        self.scope, self.receive, self.send\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "    )\n",
      "    ^\n",
      "  File \"/Users/amitpatel/Developer/PythonFiles/Image-Classification-Cat-v-Dog/.venv/lib/python3.13/site-packages/uvicorn/middleware/proxy_headers.py\", line 60, in __call__\n",
      "    return await self.app(scope, receive, send)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/amitpatel/Developer/PythonFiles/Image-Classification-Cat-v-Dog/.venv/lib/python3.13/site-packages/fastapi/applications.py\", line 1082, in __call__\n",
      "    await super().__call__(scope, receive, send)\n",
      "  File \"/Users/amitpatel/Developer/PythonFiles/Image-Classification-Cat-v-Dog/.venv/lib/python3.13/site-packages/starlette/applications.py\", line 113, in __call__\n",
      "    await self.middleware_stack(scope, receive, send)\n",
      "  File \"/Users/amitpatel/Developer/PythonFiles/Image-Classification-Cat-v-Dog/.venv/lib/python3.13/site-packages/starlette/middleware/errors.py\", line 186, in __call__\n",
      "    raise exc\n",
      "  File \"/Users/amitpatel/Developer/PythonFiles/Image-Classification-Cat-v-Dog/.venv/lib/python3.13/site-packages/starlette/middleware/errors.py\", line 164, in __call__\n",
      "    await self.app(scope, receive, _send)\n",
      "  File \"/Users/amitpatel/Developer/PythonFiles/Image-Classification-Cat-v-Dog/.venv/lib/python3.13/site-packages/gradio/brotli_middleware.py\", line 74, in __call__\n",
      "    return await self.app(scope, receive, send)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/amitpatel/Developer/PythonFiles/Image-Classification-Cat-v-Dog/.venv/lib/python3.13/site-packages/gradio/route_utils.py\", line 882, in __call__\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"/Users/amitpatel/Developer/PythonFiles/Image-Classification-Cat-v-Dog/.venv/lib/python3.13/site-packages/starlette/middleware/exceptions.py\", line 63, in __call__\n",
      "    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)\n",
      "  File \"/Users/amitpatel/Developer/PythonFiles/Image-Classification-Cat-v-Dog/.venv/lib/python3.13/site-packages/starlette/_exception_handler.py\", line 53, in wrapped_app\n",
      "    raise exc\n",
      "  File \"/Users/amitpatel/Developer/PythonFiles/Image-Classification-Cat-v-Dog/.venv/lib/python3.13/site-packages/starlette/_exception_handler.py\", line 42, in wrapped_app\n",
      "    await app(scope, receive, sender)\n",
      "  File \"/Users/amitpatel/Developer/PythonFiles/Image-Classification-Cat-v-Dog/.venv/lib/python3.13/site-packages/starlette/routing.py\", line 716, in __call__\n",
      "    await self.middleware_stack(scope, receive, send)\n",
      "  File \"/Users/amitpatel/Developer/PythonFiles/Image-Classification-Cat-v-Dog/.venv/lib/python3.13/site-packages/starlette/routing.py\", line 736, in app\n",
      "    await route.handle(scope, receive, send)\n",
      "  File \"/Users/amitpatel/Developer/PythonFiles/Image-Classification-Cat-v-Dog/.venv/lib/python3.13/site-packages/starlette/routing.py\", line 290, in handle\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"/Users/amitpatel/Developer/PythonFiles/Image-Classification-Cat-v-Dog/.venv/lib/python3.13/site-packages/starlette/routing.py\", line 78, in app\n",
      "    await wrap_app_handling_exceptions(app, request)(scope, receive, send)\n",
      "  File \"/Users/amitpatel/Developer/PythonFiles/Image-Classification-Cat-v-Dog/.venv/lib/python3.13/site-packages/starlette/_exception_handler.py\", line 53, in wrapped_app\n",
      "    raise exc\n",
      "  File \"/Users/amitpatel/Developer/PythonFiles/Image-Classification-Cat-v-Dog/.venv/lib/python3.13/site-packages/starlette/_exception_handler.py\", line 42, in wrapped_app\n",
      "    await app(scope, receive, sender)\n",
      "  File \"/Users/amitpatel/Developer/PythonFiles/Image-Classification-Cat-v-Dog/.venv/lib/python3.13/site-packages/starlette/routing.py\", line 75, in app\n",
      "    response = await f(request)\n",
      "               ^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/amitpatel/Developer/PythonFiles/Image-Classification-Cat-v-Dog/.venv/lib/python3.13/site-packages/fastapi/routing.py\", line 308, in app\n",
      "    raw_response = await run_endpoint_function(\n",
      "                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "    ...<3 lines>...\n",
      "    )\n",
      "    ^\n",
      "  File \"/Users/amitpatel/Developer/PythonFiles/Image-Classification-Cat-v-Dog/.venv/lib/python3.13/site-packages/fastapi/routing.py\", line 219, in run_endpoint_function\n",
      "    return await dependant.call(**values)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/amitpatel/Developer/PythonFiles/Image-Classification-Cat-v-Dog/.venv/lib/python3.13/site-packages/gradio/routes.py\", line 1664, in get_upload_progress\n",
      "    await asyncio.wait_for(\n",
      "        file_upload_statuses.is_tracked(upload_id), timeout=3\n",
      "    )\n",
      "  File \"/opt/homebrew/Cellar/python@3.13/3.13.7/Frameworks/Python.framework/Versions/3.13/lib/python3.13/asyncio/tasks.py\", line 507, in wait_for\n",
      "    return await fut\n",
      "           ^^^^^^^^^\n",
      "  File \"/Users/amitpatel/Developer/PythonFiles/Image-Classification-Cat-v-Dog/.venv/lib/python3.13/site-packages/gradio/route_utils.py\", line 528, in is_tracked\n",
      "    return await self._signals[upload_id].wait()\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/homebrew/Cellar/python@3.13/3.13.7/Frameworks/Python.framework/Versions/3.13/lib/python3.13/asyncio/locks.py\", line 210, in wait\n",
      "    fut = self._get_loop().create_future()\n",
      "          ~~~~~~~~~~~~~~^^\n",
      "  File \"/opt/homebrew/Cellar/python@3.13/3.13.7/Frameworks/Python.framework/Versions/3.13/lib/python3.13/asyncio/mixins.py\", line 20, in _get_loop\n",
      "    raise RuntimeError(f'{self!r} is bound to a different event loop')\n",
      "RuntimeError: <asyncio.locks.Event object at 0x129474d70 [unset]> is bound to a different event loop\n",
      "ERROR:    Exception in ASGI application\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/amitpatel/Developer/PythonFiles/Image-Classification-Cat-v-Dog/.venv/lib/python3.13/site-packages/uvicorn/protocols/http/h11_impl.py\", line 403, in run_asgi\n",
      "    result = await app(  # type: ignore[func-returns-value]\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "        self.scope, self.receive, self.send\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "    )\n",
      "    ^\n",
      "  File \"/Users/amitpatel/Developer/PythonFiles/Image-Classification-Cat-v-Dog/.venv/lib/python3.13/site-packages/uvicorn/middleware/proxy_headers.py\", line 60, in __call__\n",
      "    return await self.app(scope, receive, send)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/amitpatel/Developer/PythonFiles/Image-Classification-Cat-v-Dog/.venv/lib/python3.13/site-packages/fastapi/applications.py\", line 1082, in __call__\n",
      "    await super().__call__(scope, receive, send)\n",
      "  File \"/Users/amitpatel/Developer/PythonFiles/Image-Classification-Cat-v-Dog/.venv/lib/python3.13/site-packages/starlette/applications.py\", line 113, in __call__\n",
      "    await self.middleware_stack(scope, receive, send)\n",
      "  File \"/Users/amitpatel/Developer/PythonFiles/Image-Classification-Cat-v-Dog/.venv/lib/python3.13/site-packages/starlette/middleware/errors.py\", line 186, in __call__\n",
      "    raise exc\n",
      "  File \"/Users/amitpatel/Developer/PythonFiles/Image-Classification-Cat-v-Dog/.venv/lib/python3.13/site-packages/starlette/middleware/errors.py\", line 164, in __call__\n",
      "    await self.app(scope, receive, _send)\n",
      "  File \"/Users/amitpatel/Developer/PythonFiles/Image-Classification-Cat-v-Dog/.venv/lib/python3.13/site-packages/gradio/brotli_middleware.py\", line 74, in __call__\n",
      "    return await self.app(scope, receive, send)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/amitpatel/Developer/PythonFiles/Image-Classification-Cat-v-Dog/.venv/lib/python3.13/site-packages/gradio/route_utils.py\", line 882, in __call__\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"/Users/amitpatel/Developer/PythonFiles/Image-Classification-Cat-v-Dog/.venv/lib/python3.13/site-packages/starlette/middleware/exceptions.py\", line 63, in __call__\n",
      "    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)\n",
      "  File \"/Users/amitpatel/Developer/PythonFiles/Image-Classification-Cat-v-Dog/.venv/lib/python3.13/site-packages/starlette/_exception_handler.py\", line 53, in wrapped_app\n",
      "    raise exc\n",
      "  File \"/Users/amitpatel/Developer/PythonFiles/Image-Classification-Cat-v-Dog/.venv/lib/python3.13/site-packages/starlette/_exception_handler.py\", line 42, in wrapped_app\n",
      "    await app(scope, receive, sender)\n",
      "  File \"/Users/amitpatel/Developer/PythonFiles/Image-Classification-Cat-v-Dog/.venv/lib/python3.13/site-packages/starlette/routing.py\", line 716, in __call__\n",
      "    await self.middleware_stack(scope, receive, send)\n",
      "  File \"/Users/amitpatel/Developer/PythonFiles/Image-Classification-Cat-v-Dog/.venv/lib/python3.13/site-packages/starlette/routing.py\", line 736, in app\n",
      "    await route.handle(scope, receive, send)\n",
      "  File \"/Users/amitpatel/Developer/PythonFiles/Image-Classification-Cat-v-Dog/.venv/lib/python3.13/site-packages/starlette/routing.py\", line 290, in handle\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"/Users/amitpatel/Developer/PythonFiles/Image-Classification-Cat-v-Dog/.venv/lib/python3.13/site-packages/starlette/routing.py\", line 78, in app\n",
      "    await wrap_app_handling_exceptions(app, request)(scope, receive, send)\n",
      "  File \"/Users/amitpatel/Developer/PythonFiles/Image-Classification-Cat-v-Dog/.venv/lib/python3.13/site-packages/starlette/_exception_handler.py\", line 53, in wrapped_app\n",
      "    raise exc\n",
      "  File \"/Users/amitpatel/Developer/PythonFiles/Image-Classification-Cat-v-Dog/.venv/lib/python3.13/site-packages/starlette/_exception_handler.py\", line 42, in wrapped_app\n",
      "    await app(scope, receive, sender)\n",
      "  File \"/Users/amitpatel/Developer/PythonFiles/Image-Classification-Cat-v-Dog/.venv/lib/python3.13/site-packages/starlette/routing.py\", line 75, in app\n",
      "    response = await f(request)\n",
      "               ^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/amitpatel/Developer/PythonFiles/Image-Classification-Cat-v-Dog/.venv/lib/python3.13/site-packages/fastapi/routing.py\", line 308, in app\n",
      "    raw_response = await run_endpoint_function(\n",
      "                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "    ...<3 lines>...\n",
      "    )\n",
      "    ^\n",
      "  File \"/Users/amitpatel/Developer/PythonFiles/Image-Classification-Cat-v-Dog/.venv/lib/python3.13/site-packages/fastapi/routing.py\", line 219, in run_endpoint_function\n",
      "    return await dependant.call(**values)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/amitpatel/Developer/PythonFiles/Image-Classification-Cat-v-Dog/.venv/lib/python3.13/site-packages/gradio/routes.py\", line 1664, in get_upload_progress\n",
      "    await asyncio.wait_for(\n",
      "        file_upload_statuses.is_tracked(upload_id), timeout=3\n",
      "    )\n",
      "  File \"/opt/homebrew/Cellar/python@3.13/3.13.7/Frameworks/Python.framework/Versions/3.13/lib/python3.13/asyncio/tasks.py\", line 507, in wait_for\n",
      "    return await fut\n",
      "           ^^^^^^^^^\n",
      "  File \"/Users/amitpatel/Developer/PythonFiles/Image-Classification-Cat-v-Dog/.venv/lib/python3.13/site-packages/gradio/route_utils.py\", line 528, in is_tracked\n",
      "    return await self._signals[upload_id].wait()\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/homebrew/Cellar/python@3.13/3.13.7/Frameworks/Python.framework/Versions/3.13/lib/python3.13/asyncio/locks.py\", line 210, in wait\n",
      "    fut = self._get_loop().create_future()\n",
      "          ~~~~~~~~~~~~~~^^\n",
      "  File \"/opt/homebrew/Cellar/python@3.13/3.13.7/Frameworks/Python.framework/Versions/3.13/lib/python3.13/asyncio/mixins.py\", line 20, in _get_loop\n",
      "    raise RuntimeError(f'{self!r} is bound to a different event loop')\n",
      "RuntimeError: <asyncio.locks.Event object at 0x129474d70 [unset]> is bound to a different event loop\n"
     ]
    }
   ],
   "source": [
    "import gradio as gr\n",
    "import tensorflow as tf\n",
    "from tensorflow.keras.models import load_model\n",
    "from PIL import Image\n",
    "import numpy as np\n",
    "import os\n",
    "\n",
    "# --- Configuration ---\n",
    "MODEL_PATH = 'cat_dog_cnn_91_accuracy.h5'\n",
    "IMAGE_SIZE = (150, 150) # Must match your training size\n",
    "CLASS_LABELS = ['Cat', 'Dog'] # Labels based on generator's class_indices (Cat=0, Dog=1)\n",
    "# ---------------------\n",
    "\n",
    "# 1. Load the Model\n",
    "try:\n",
    "    model = load_model(MODEL_PATH)\n",
    "    print(f\" Model '{MODEL_PATH}' loaded successfully.\")\n",
    "except Exception as e:\n",
    "    print(f\" ERROR: Could not load model '{MODEL_PATH}'. Please ensure the file is in the same directory.\")\n",
    "    print(f\"Error details: {e}\")\n",
    "    # Exit or raise error if the model is crucial\n",
    "    raise\n",
    "\n",
    "# 2. Define the Prediction Function\n",
    "def predict_image_gradio(input_img):\n",
    "    \"\"\"\n",
    "    Takes a PIL Image object (provided by Gradio) and returns the prediction result.\n",
    "    \"\"\"\n",
    "    if input_img is None:\n",
    "        return \"Please upload an image.\"\n",
    "\n",
    "    # 1. Pre-process the image\n",
    "    img = input_img.convert('RGB')\n",
    "    img = img.resize(IMAGE_SIZE)\n",
    "    img_array = np.asarray(img)\n",
    "    \n",
    "    # Add batch dimension and normalize (divide by 255.0)\n",
    "    # Shape changes from (150, 150, 3) to (1, 150, 150, 3)\n",
    "    img_batch = np.expand_dims(img_array, axis=0) / 255.0\n",
    "\n",
    "    # 2. Make Prediction\n",
    "    # The output is a single value between 0 and 1 (due to sigmoid)\n",
    "    raw_prediction = model.predict(img_batch, verbose=0)[0][0]\n",
    "    \n",
    "    # 3. Interpret Result (Cat=0, Dog=1)\n",
    "    if raw_prediction < 0.5:\n",
    "        # Closer to 0 means Cat\n",
    "        label_index = 0\n",
    "        confidence_score = 1.0 - raw_prediction\n",
    "    else:\n",
    "        # Closer to 1 means Dog\n",
    "        label_index = 1\n",
    "        confidence_score = raw_prediction\n",
    "\n",
    "    # Create a dictionary for Gradio's Label output format\n",
    "    # The keys must be the class labels\n",
    "    predictions = {\n",
    "        CLASS_LABELS[0]: 1.0 - confidence_score,  # The probability of the opposite class\n",
    "        CLASS_LABELS[1]: confidence_score\n",
    "    }\n",
    "    # Adjust the dictionary to ensure the predicted class has the high confidence\n",
    "    final_output = {\n",
    "        CLASS_LABELS[0]: 1.0 - confidence_score if label_index == 1 else confidence_score,\n",
    "        CLASS_LABELS[1]: confidence_score if label_index == 1 else 1.0 - confidence_score\n",
    "    }\n",
    "    \n",
    "    return final_output\n",
    "\n",
    "# 3. Create the Gradio Interface\n",
    "iface = gr.Interface(\n",
    "    fn=predict_image_gradio,\n",
    "    inputs=gr.Image(type=\"pil\", label=\"Upload Cat or Dog Image\"),\n",
    "    outputs=gr.Label(num_top_classes=2, label=\"Prediction\"),\n",
    "    title=\"Convolutional Cat vs. Dog Classifier\",\n",
    "    description=\"Upload an image to see if the CNN model classifies it as a Cat or a Dog.\",\n",
    "    examples=[\n",
    "        # Optional: Add paths to example images here for quick testing\n",
    "        # e.g., [\"path/to/example_cat.jpg\"],\n",
    "        # e.g., [\"path/to/example_dog.jpg\"]\n",
    "    ],\n",
    "    allow_flagging='never' # Disables the \"Flag\" button\n",
    ")\n",
    "iface.launch()\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": ".venv",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
